version: '2'
services:
  postgresqldb:
    image: postgres:latest
    environment:
      - POSTGRES_DB=passport_manage
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - ./share/:/share/
  app:
    container_name: managing
    image: managin_passports:latest
    environment:
      - PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresqldb:5432/passport_manage
    ports:
      - '8080:8080'
    depends_on:
      - postgresqldb

